### ISSUE TITLE
Support optional rules when parsing

### ISSUE THREAD

**Issue by codemonstur** [sylvainhalle/Bullwinkle#14]
I'm trying to use Bullwinkle to parse the BNF for Java. So I grabbed the code, downloaded the Java BNF from here: https://cs.au.dk/~amoeller/RegAut/JavaBNF.html. Did some editing to clean things up and wrote this code:

    public static void main(final String... args) throws InvalidGrammarException, ParseException {
        InputStream stream = new ByteArrayInputStream("""
                <package_declaration> := package <package_name>? ;
                <package_name> := ^[a-z]+
                """.getBytes(UTF_8));

        BnfParser parser = new BnfParser(stream);
        ParseNode tree = parser.parse("""
            package boe;
            class Test {
                public static void main(String[] args) {
                    System.out.println("Hello, world!");
                }
            }""");
        System.out.println(tree);
    }

I had to change the parsing in getRules to stop using semicolons for the end of rules and instead look at line endings. After that change and running the code I get this error:

    Exception in thread "main" Cannot find rule for token <package_name>?
	    at ca.uqac.lif.bullwinkle.BnfParser.parse(BnfParser.java:542)
	    at ca.uqac.lif.bullwinkle.BnfParser.parse(BnfParser.java:457)
	    at examples.JavaParsing.main(JavaParsing.java:23)

This is problematic because the Java BNF is filled with optional rules:

    <compilation unit> := <package declaration>? <import declarations>? <type declarations>?
    <class declaration> := <class modifiers>? class <identifier> <super>? <interfaces>? <class body>
    <class body> := { <class body declarations>? }
    <constructor declaration> := <constructor modifiers>? <constructor declarator> <throws>? <constructor body>
    <constructor declarator> := <simple type name> ( <formal parameter list>? )

and more.

I'd love to be able to parse Java with bullwinkle. Thanks.

**Comment by sylvainhalle** [comment]
Optional rules are supported in Bullwinkle, but they have to be written following the BNF syntax, where the "?" symbol is not allowed. So instead of writing:

```
<S> := <A> <B>?;
```

you should write instead:

```
<S> := <A> <B> | <A>;
```

There are two ways to parse S: either as A followed by B, or as A alone --which has the effect of making B optional.

**Comment by codemonstur** [comment]
I came to the same conclusion. But I felt re-writing the whole Java BNF this way would be too much work and would make for a really ugly BNF anyway. So I added the feature myself.

I'm thinking of sharing the code but will wait until Bullwinkle is released under MIT.

**Comment by sylvainhalle** [comment]
I just changed the header comments to the MIT license.
